### ISSUE TITLE
500 Error when repeating a Markdown notice or remote following.

### ISSUE THREAD

**Issue by faulteh** [chimo/gs-markdown#7]
So I just tried to repeat a notice on my own instance (which has Markdown enabled). The notice came from the TasLUG instance and was a Markdown notice. This also just happened when I tried to remote follow you, it popped back with a 500 server error. It looks like it's trying to make a special type of notice (eg "xxx repeated this", or "xxx started following yyy") which doesn't have the hasParent() method, which is something you added recently to fix the common_linkify_mentions() call.

Error when trying to follow you:

2016-01-10 05:45:35 LOG_ERR: [scriptforge.org:7566.c731c866 POST /main/ostatussub] ServerErrorAction: 500 Call to undefined method Notice::hasParent
#0 /home/scriptforge/www.scriptforge.org/plugins/Markdown/MarkdownPlugin.php(28): Safe_DataObject->__call('hasParent', Array)
#1 /home/scriptforge/www.scriptforge.org/plugins/Markdown/MarkdownPlugin.php(28): Notice->hasParent()
#2 [internal function]: MarkdownPlugin->onStartNoticeSave(Object(Notice))
#3 /home/scriptforge/www.scriptforge.org/lib/event.php(105): call_user_func_array(Array, Array)
#4 /home/scriptforge/www.scriptforge.org/classes/Notice.php(652): Event::handle('StartNoticeSave', Array)
#5 /home/scriptforge/www.scriptforge.org/plugins/Activity/ActivityPlugin.php(97): Notice::saveNew('1', 'Scott Bragg (ht...', 'activity', Array)
#6 [internal function]: ActivityPlugin->onEndSubscribe(Object(Profile), Object(Profile))
#7 /home/scriptforge/www.scriptforge.org/lib/event.php(105): call_user_func_array(Array, Array)
#8 /home/scriptforge/www.scriptforge.org/classes/Subscription.php(132): Event::handle('EndSubscribe', Array)
#9 /home/scriptforge/www.scriptforge.org/plugins/OStatus/actions/ostatussub.php(320): Subscription::start(Object(Profile), Object(Profile))
#10 /home/scriptforge/www.scriptforge.org/plugins/OStatus/actions/ostatussub.php(347): OStatusSubAction->saveFeed()
#11 /home/scriptforge/www.scriptforge.org/plugins/OStatus/actions/ostatussub.php(69): OStatusSubAction->handlePost()
#12 /home/scriptforge/www.scriptforge.org/lib/action.php(124): OStatusSubAction->handle(Array)
#13 /home/scriptforge/www.scriptforge.org/lib/action.php(101): Action->execute(Array)
#14 [internal function]: Action::run(Array)
#15 /home/scriptforge/www.scriptforge.org/index.php(316): call_user_func('OstatussubActio...', Array)
#16 /home/scriptforge/www.scriptforge.org/index.php(330): main()
#17 {main}

Error when trying to repeat a notice:

2016-01-10 05:48:07 LOG_ERR: [scriptforge.org:7848.fbe2e70f POST /main/repeat] ServerErrorAction: 500 Call to undefined method Notice::hasParent
#0 /home/scriptforge/www.scriptforge.org/plugins/Markdown/MarkdownPlugin.php(28): Safe_DataObject->__call('hasParent', Array)
#1 /home/scriptforge/www.scriptforge.org/plugins/Markdown/MarkdownPlugin.php(28): Notice->hasParent()
#2 [internal function]: MarkdownPlugin->onStartNoticeSave(Object(Notice))
#3 /home/scriptforge/www.scriptforge.org/lib/event.php(105): call_user_func_array(Array, Array)
#4 /home/scriptforge/www.scriptforge.org/classes/Notice.php(652): Event::handle('StartNoticeSave', Array)
#5 /home/scriptforge/www.scriptforge.org/classes/Notice.php(2154): Notice::saveNew('1', 'RT @taslug Hoba...', 'web', Array)
#6 /home/scriptforge/www.scriptforge.org/plugins/Share/actions/repeat.php(67): Notice->repeat(Object(Profile), 'web')
#7 /home/scriptforge/www.scriptforge.org/lib/managedaction.php(40): RepeatAction->doPreparation()
#8 /home/scriptforge/www.scriptforge.org/lib/formaction.php(51): ManagedAction->prepare(Array)
#9 /home/scriptforge/www.scriptforge.org/lib/action.php(122): FormAction->prepare(Array)
#10 /home/scriptforge/www.scriptforge.org/lib/action.php(101): Action->execute(Array)
#11 [internal function]: Action::run(Array)
#12 /home/scriptforge/www.scriptforge.org/index.php(316): call_user_func('RepeatAction::r...', Array)
#13 /home/scriptforge/www.scriptforge.org/index.php(330): main()
#14 {main}

**Comment by faulteh** [comment]
Refer to #8 for my workaround. It certainly clears the issue but perhaps instead should check for the notice types were are interested in applying Markdown (is that in the API?)

**Comment by faulteh** [comment]
Pull request merged so this is fixed now.
